development:
  adapter: postgresql
  encoding: utf8
  database: demandealanuit_development
  pool: 5
  username: axelrigaud
  password: 

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: demandealanuit_test
  pool: 5
  username: 
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: demandealanuit_production
  pool: 5
  username: 
  password:
